### PR TITLE
144 learningpath fontsize

### PR DESCRIPTION
**Pull request by stef-barburou**
fixes the changing fontsize (setting everything to 1.8rem right off the bat

fixes the links that appear in the cards when visited.

### CODE REVIEW

**Review by romy-piche — APPROVED** [review]
💯

**Comment by kroussea** [comment]
I mean I have no objection on the changes, but it affects all paragraphs of the application, that do not have an override of the base font-size. So this page for example: /en/ep-77-en

The paragraphs font size are increased considerably, almost as similar to an h2 in some cases here
image
vs before with 1.4rem on p:
image

and the content on /en/learning-paths
image
vs before:
image

I didn't make the initial design so I have no word on this, but perhaps we could ask some designer, either former designer of the project or someone else? idk just making sure we aren't going to be yelled at!

**Review by kroussea — APPROVED** [review]

**Comment by stef-barburou** [comment]
valid. the comms message was that they should both be the same, unclear if they should be the same "bigger" or same "smaller "

**Comment by stef-barburou** [comment]
since every other page is at 1.8rem and learningPath is the exception and from what I understand a customization, I'd say go for 1.8rem

**Pull request merged**
